  window.STRAINS = [
  { name: "24k Gold", type: "hybrid-strain", url: "https://www.leafly.com/strains/24k-gold" },
  { name: "91 Octane", type: "hybrid-strain", url: "https://www.leafly.com/strains/91-octane" },
  { name: "9lb Hammer", type: "indica-strain", url: "https://www.leafly.com/strains/9-pound-hammer" },
  { name: "Abominable Snowman", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/abominable-snowman" },	
  { name: "AC/DC", type: "hybrid-strain", url: "https://www.leafly.com/strains/acdc" },	
  { name: "Acapulco Gold", type: "sativa-strain", url: "https://www.leafly.com/strains/acapulco-gold" },	
  { name: "Ace Killer OG", type: "indica-strain", url: "https://www.leafly.com/strains/ace-killer-og" },	
  { name: "Ace of Spades", type: "hybrid-strain", url: "https://www.leafly.com/strains/ace-of-spades" },	
  { name: "Afghani", type: "indica-strain", url: "https://www.leafly.com/strains/afghani" },	
  { name: "Afghani Skunk", type: "hybrid-strain", url: "https://www.leafly.com/strains/afghan-skunk" },	
  { name: "Afgoo", type: "indica-strain", url: "https://www.leafly.com/strains/afgoo" },	
  { name: "AK 47", type: "hybrid-strain", url: "https://www.leafly.com/strains/ak-47" },	
  { name: "AK Kush", type: "indica-strain", url: "https://www.leafly.com/strains/ak-kush" },	
  { name: "Alaskan Thunder Fuck", type: "sativa-strain", url: "https://www.leafly.com/strains/alaskan-thunder-fuck" },	
  { name: "Alien Guy", type: "indica-strain", url: "https://www.leafly.com/strains/alien-guy" },	
  { name: "Alien OG", type: "hybrid-strain", url: "https://www.leafly.com/strains/alien-og" },	
  { name: "Alien Rift", type: "indica-strain", url: "https://www.leafly.com/strains/alien-rift" },	
  { name: "Animal Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/animal-cookies" },	
  { name: "Animal Face", type: "hybrid-strain", url: "https://www.leafly.com/strains/animal-face" },	
  { name: "Animal Mints", type: "hybrid-strain", url: "https://www.leafly.com/strains/animal-mints" },	
  { name: "Animal Sundae", type: "hybrid-strain", url: "https://www.leafly.com/strains/animal-sundae" },	
  { name: "Apple Fritter", type: "hybrid-strain", url: "https://www.leafly.com/strains/apple-fritter" },	
  { name: "Apple Jacks", type: "sativa-strain", url: "https://weedmaps.com/strains/apple-jack" },	
  { name: "Atom Splitter", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/atom-splitter" },	
  { name: "Aurora Borealis", type: "indica-strain", url: "https://www.leafly.com/strains/aurora-borealis" },	
  { name: "Bad Azz OG", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/bad-azz-kush" },	
  { name: "Bakerstreet", type: "indica-strain", url: "https://www.leafly.com/strains/bakerstreet" },	
  { name: "Banana Cream", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/banana-cream" },	
  { name: "Banana Cream Pie", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/banana-cream-pie" },	
  { name: "Banana Fig", type: "indica-strain", url: "https://www.leafly.com/strains/banana-fig" },	
  { name: "Banana Fruit Punch", type: "hybrid-strain", url: "https://weedmaps.com/strains/banana-punch" },	
  { name: "Banana Ice", type: "hybrid-strain", url: "https://weedmaps.com/strains/banana-ice-cream" },	
  { name: "Banana OG", type: "indica-strain", url: "https://www.leafly.com/strains/banana-og" },	
  { name: "Batman OG", type: "indica-strain", url: "https://www.leafly.com/strains/batman-og" },	
  { name: "Beast Mode Skittles", type: "sativa-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/beast-mode-skittles" },	
  { name: "Berry Gelato", type: "indica-strain", url: "https://www.leafly.com/strains/berry-gelato" },	
  { name: "Big Cat Kush", type: "indica-strain", url: "https://kushstation.co/product/big-cat-kush/" },	
  { name: "Big Mac", type: "indica-strain", url: "https://www.leafly.com/strains/big-mac" },	
  { name: "Birthday Cake Kush", type: "indica-strain", url: "https://www.leafly.com/strains/birthday-cake-kush" },	
  { name: "Biscotti Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/biscotti-cookies" },	
  { name: "Black Biscotti", type: "indica-strain", url: "https://www.leafly.com/strains/black-scotti" },	
  { name: "Black Cheese", type: "indica-strain", url: "https://www.leafly.com/strains/black-cheese" },	
  { name: "Black Cherry Gelato", type: "hybrid-strain", url: "https://www.leafly.com/strains/black-cherry-gelato" },	
  { name: "Black Diamond", type: "indica-strain", url: "https://www.leafly.com/strains/black-diamond" },	
  { name: "Black Gas", type: "hybrid-strain", url: "https://www.leafly.com/strains/black-gas" },	
  { name: "Black Jelly", type: "indica-strain", url: "https://www.leafly.com/strains/black-jelly" },	
  { name: "Black Kyber Crystal", type: "indica-strain", url: "https://www.leafly.com/strains/black-kyber-crystal" },	
  { name: "Black Mamba", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/black-mamba" },	
  { name: "Black Rose", type: "indica-strain", url: "https://www.leafly.com/strains/black-roses" },	
  { name: "Black Scout", type: "unknown-strain", url: "" },
  { name: "Blackberry Cheesecake", type: "indica-strain", url: "https://www.leafly.com/strains/blackberry-cheesecake" },	
  { name: "Blackberry Kush", type: "indica-strain", url: "https://www.leafly.com/strains/blackberry-kush" },	
  { name: "Blackberry Moonrocks", type: "indica-strain", url: "https://www.leafly.com/strains/blackberry-moonrocks" },	
  { name: "Blood Orange Haze", type: "hybrid-strain", url: "https://seedfinder.eu/en/strain-info/blood-orange-haze/mephisto-genetics" },	
  { name: "Blue Gelato", type: "hybrid-strain", url: "https://www.leafly.com/strains/blue-gelato" },	
  { name: "Blue Lights", type: "indica-strain", url: "https://www.leafly.com/strains/blue-lights" },	
  { name: "Blue Magoo Cookies", type: "hybrid-strain", url: "https://wccannabis.cc/product/blue-magoo-cookies-aaaa/" },	
  { name: "Blue Slushie", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/blue-slushie" },	
  { name: "Blue Tahoe", type: "hybrid-strain", url: "https://www.leafly.com/strains/blue-tahoe" },	
  { name: "Blue Venom", type: "indica-strain", url: "https://www.leafly.com/strains/blue-venom" },	
  { name: "Blue Widow", type: "hybrid-strain", url: "https://www.leafly.com/strains/blue-widow" },	
  { name: "Blue Zlushies", type: "hybrid-strain", url: "https://www.leafly.com/strains/blue-zlushies" },	
  { name: "Blueberry", type: "indica-strain", url: "https://www.leafly.com/strains/blueberry" },	
  { name: "Blueberry Cheesecake", type: "hybrid-strain", url: "https://www.leafly.com/strains/blueberry-cheesecake" },	
  { name: "Blueberry Donuts", type: "hybrid-strain", url: "https://bulkweedbc.cc/blueberry-donuts/" },	
  { name: "Blueberry Icewreck", type: "hybrid-strain", url: "https://bulkweedinbox.cc/product/blueberry-icewreck/" },	
  { name: "Blueberry Kush", type: "indica-strain", url: "https://www.leafly.com/strains/blueberry-kush" },	
  { name: "Blueberry Rockstar", type: "indica-strain", url: "https://budexpressnow.co/product/blueberry-rockstar-aaaa-popcorn/" },	
  { name: "Blueberry Seagal", type: "indica-strain", url: "https://kushstation.co/unraveling-the-blueberry-seagal-strain-mystery/" },	
  { name: "Brainstorm Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/brainstorm-haze" },	
  { name: "Brownie Scout", type: "indica-strain", url: "https://www.leafly.com/strains/brownie-scout" },	
  { name: "Bruce Banner", type: "hybrid-strain", url: "https://www.leafly.com/strains/bruce-banner" },	
  { name: "Bubba Breath", type: "indica-strain", url: "https://www.leafly.com/strains/bubbas-breath" },	
  { name: "Bubba Kush", type: "indica-strain", url: "https://www.leafly.com/strains/bubba-kush" },	
  { name: "Bubble Bath", type: "indica-strain", url: "https://www.leafly.com/strains/bubble-bath" },	
  { name: "Cake Pop", type: "hybrid-strain", url: "https://www.leafly.com/strains/cake-pop" },	
  { name: "Cali 47", type: "sativa-strain", url: "https://www.leafly.com/strains/kali-47" },	
  { name: "Cali Bubba", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/cali-bubba" },	
  { name: "Cali Cookies", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/cali-cookies" },	
  { name: "Cali Dragon", type: "indica-strain", url: "https://www.leafly.com/strains/cali-dragon" },	
  { name: "Cali Gas", type: "indica-strain", url: "https://www.leafly.com/strains/cali-gas" },	
  { name: "Cali Gold", type: "indica-strain", url: "https://www.leafly.com/strains/cali-gold" },	
  { name: "Candy Land", type: "sativa-strain", url: "https://wccannabis.cc/product/candy-land-aaaa/" },	
  { name: "Cannalope Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/cannalope-haze" },	
  { name: "Cap Junky", type: "hybrid-strain", url: "https://www.leafly.com/strains/cap-junky" },	
  { name: "Caramel Cookies", type: "indica-strain", url: "https://cheapweed.io/shop/marijuana-flowers/hybrid/caramel-cookies/" },	
  { name: "Caribbean Cream", type: "indica-strain", url: "https://wccannabis.cc/product/caribbean-creme-aaa/" },	
  { name: "Cashmere", type: "indica-strain", url: "https://www.leafly.com/strains/cashmere" },	
  { name: "Cat Piss", type: "sativa-strain", url: "https://www.leafly.com/strains/cat-piss" },	
  { name: "Cereal Milk", type: "hybrid-strain", url: "https://www.leafly.com/strains/cereal-milk" },	
  { name: "Champagne Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/champagne-kush" },	
  { name: "Cherry Bomb", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/cherry-bomb/?page=15" },
  { name: "Chem Fire", type: "indica-strain", url: "https://www.leafly.com/strains/chem-fire" },	
  { name: "Chem La Chem", type: "sativa-strain", url: "https://www.leafly.com/strains/chem-de-la-chem" },	
  { name: "Chemdawg", type: "hybrid-strain", url: "https://www.leafly.com/strains/chemdawg" },	
  { name: "Chemdog #4", type: "hybrid-strain", url: "https://www.leafly.com/strains/chemdawg-4" },	
  { name: "Chernobyl", type: "sativa-strain", url: "https://www.leafly.com/strains/chernobyl" },	
  { name: "Cherry Cosmo", type: "hybrid-strain", url: "https://www.leafly.com/strains/cherry-cosmo" },	
  { name: "Cherry Cough", type: "indica-strain", url: "https://www.leafly.com/strains/cherry-cough" },	
  { name: "Cherry OG", type: "hybrid-strain", url: "https://www.leafly.com/strains/cherry-og" },	
  { name: "Chocolate OG", type: "indica-strain", url: "https://www.leafly.com/strains/chocolate-og" },	
  { name: "Chocolope", type: "sativa-strain", url: "https://www.leafly.com/strains/chocolope" },	
  { name: "Chronic Thunder", type: "indica-strain", url: "https://www.leafly.com/strains/chronic-thunder" },	
  { name: "Cinderella 99", type: "sativa-strain", url: "https://www.leafly.com/strains/cinderella-99" },	
  { name: "Cobra Lips", type: "indica-strain", url: "https://www.leafly.com/strains/cobra-lips" },	
  { name: "Coffee Creamer", type: "hybrid-strain", url: "https://www.leafly.com/strains/coffee-creamer" },	
  { name: "Cold Creek Kush", type: "indica-strain", url: "https://www.leafly.com/strains/cold-creek-kush" },	
  { name: "Colt 45", type: "hybrid-strain", url: "https://www.leafly.com/strains/colt-45" },	
  { name: "Comatose", type: "indica-strain", url: "https://wccannabis.cc/product/comatose-og-aa/" },	
  { name: "Compact Crushers", type: "indica-strain", url: "https://www.budlafleur.com/portfolio/compac-crushers-flower/" },	
  { name: "Confidential Cheese", type: "indica-strain", url: "https://www.leafly.com/strains/confidential-cheese" },	
  { name: "Cookie Dough", type: "hybrid-strain", url: "https://www.leafly.com/strains/cookie-dough" },	
  { name: "Cookie God", type: "sativa-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/cookie-god" },	
  { name: "Cookie Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/cookie-kush" },	
  { name: "Cosmic Clusters", type: "hybrid-strain", url: "https://lucidcannabis.ca/products/nebulous-cosmic-clusters" },	
  { name: "Cosmic Cream", type: "indica-strain", url: "https://valuebuds.com/products/san-rafael-71-cosmic-cream-ind-dried-35g-alberta" },	
  { name: "Couch Potato", type: "indica-strain", url: "https://www.wiidsk.ca/product/couch-potato-catch-me-outside/" },	
  { name: "Crab Cakes", type: "sativa-strain", url: "https://higherlimits.com/shop/product/skosha-crab-cakes-sativa-1g-M6272608-V3" },	
  { name: "Crazy Glue", type: "hybrid-strain", url: "https://www.leafly.com/strains/crazy-glue" },	
  { name: "Critical Orange Punch", type: "indica-strain", url: "https://www.leafly.com/strains/critical-orange-punch" },	
  { name: "Critical Purple Kush", type: "indica-strain", url: "https://www.leafly.com/strains/critical-purple-kush" },	
  { name: "Crypto Chrome", type: "hybrid-strain", url: "https://bulkweedinbox.cc/product/crypto/" },	
  { name: "Crystal Lights", type: "unknown-strain", url: "" },	
  { name: "Crystal Mountain Kush", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/crystal-mountain-kush" },	
  { name: "Cuban Linx", type: "sativa-strain", url: "https://www.leafly.com/strains/cuban-linx" },	
  { name: "Dairy Queen LSD", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/dairy-queen" },	
  { name: "Dalato", type: "indica-strain", url: "https://wccannabis.cc/product/dolato-aaa/" },	
  { name: "Dank Schrader", type: "indica-strain", url: "https://www.leafly.com/strains/dank-schrader" },	
  { name: "Dank Sinatra", type: "indica-strain", url: "https://www.leafly.com/strains/dank-sinatra" },	
  { name: "Dark Angel", type: "hybrid-strain", url: "https://www.leafly.com/strains/dark-angel" },	
  { name: "Darth Vader", type: "indica-strain", url: "https://www.leafly.com/strains/darth-vader-og" },	
  { name: "Death Bubba", type: "indica-strain", url: "https://www.leafly.com/strains/death-bubba" },	
  { name: "Death Butter Breath", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/death-bubba" },	
  { name: "Death Cookies", type: "indica-strain", url: "https://www.bulkbuddy.co/product/death-cookies-strain/" },	
  { name: "Death Gas", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica/gas" },	
  { name: "Death Reaper", type: "indica-strain", url: "https://www.kushbuddy.co/product/death-reaper/" },	
  { name: "Death Vader OG", type: "indica-strain", url: "https://www.leafly.com/strains/darth-vader-og" },	
  { name: "Death Wish", type: "indica-strain", url: "https://www.iheartjane.com/embed/stores/137/menu/products/793112/canna-culture-death-wish" },	
  { name: "Devils Triangle", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/devils-triangle" },	
  { name: "Diablo Death Bubba", type: "indica-strain", url: "https://www.supherbscanada.store/product/diablo-death-bubba/" },	
  { name: "Divorce Cake", type: "hybrid-strain", url: "https://www.leafly.com/strains/divorce-cake" },	
  { name: "Do Si Cake", type: "indica-strain", url: "https://www.leafly.com/strains/dosi-cake" },	
  { name: "Do Si Dos", type: "indica-strain", url: "https://www.leafly.com/strains/do-si-dos" },	
  { name: "Donkey Butter", type: "indica-strain", url: "https://www.leafly.com/strains/donkey-butter" },	
  { name: "Donkey Kong", type: "hybrid-strain", url: "https://www.leafly.com/strains/donkey-kong" },	
  { name: "Donny Burger", type: "indica-strain", url: "https://www.leafly.com/strains/donny-burger" },	
  { name: "Dopamine", type: "indica-strain", url: "https://greenleafexpress.io/product/aaaa-dopamine-by-kootenayz-exoticz/" },	
  { name: "Dos Diablos", type: "indica-strain", url: "https://www.bulkbuddy.co/product/dos-diablos-strain/" },	
  { name: "Dosi Cookies", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/dosi-cookies" },	
  { name: "Dosi Face", type: "hybrid-strain", url: "https://www.leafly.com/strains/dosi-face" },	
  { name: "Dosi Punch", type: "indica-strain", url: "https://www.leafly.com/strains/dosi-punch" },	
  { name: "Double Death Canopy", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/double" },	
  { name: "Double Kush Breath", type: "indica-strain", url: "https://www.leafly.com/strains/ogkb" },	
  { name: "Dragon's Breath", type: "sativa-strain", url: "https://www.leafly.com/strains/dragons-breath" },	
  { name: "Dragonfruit Gelato", type: "hybrid-strain", url: "https://www.leafly.com/strains/dragon-fruit" },	
  { name: "Duke Nukem", type: "sativa-strain", url: "https://www.leafly.com/strains/duke-nukem" },	
  { name: "Dutch Cake", type: "indica-strain", url: "https://www.leafly.com/strains/dutch-cake" },	
  { name: "El Chapo", type: "indica-strain", url: "https://www.leafly.com/strains/el-chapo" },	
  { name: "El Chemino", type: "indica-strain", url: "https://ruralbudscannabis.ca/product/daily-special-el-chimino-flower-group/" },	
  { name: "El Jefe", type: "indica-strain", url: "https://www.bulkbuddy.co/product/el-jefe-strain/" },	
  { name: "El Padrino", type: "indica-strain", url: "https://mmjexpress.cc/product/el-padrino-aaaa/" },	
  { name: "Electric Honeydew", type: "hybrid-strain", url: "https://medbud.wiki/strains/aurora-pedanios/pedanios-t26/" },	
  { name: "Electric Mountaindew", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/mt-n-dew" },	
  { name: "Emancipator", type: "indica-strain", url: "https://cannaclubco.io/product/emancipator/" },	
  { name: "Event Horizon", type: "hybrid-strain", url: "https://growdiaries.com/strains/event-horizon" },	
  { name: "Face Off OG", type: "indica-strain", url: "https://www.leafly.com/strains/face-off-og" },	
  { name: "Fat Banana", type: "indica-strain", url: "https://www.leafly.com/strains/fat-banana" },	
  { name: "Fire Breath", type: "indica-strain", url: "https://www.leafly.com/strains/dragons-breath" },	
  { name: "Fire OG", type: "indica-strain", url: "https://www.leafly.com/strains/fire-og" },	
  { name: "Flo", type: "hybrid-strain", url: "https://www.leafly.com/strains/flo" },	
  { name: "Formula 1", type: "hybrid-strain", url: "https://www.leafly.com/strains/formula-one" },	
  { name: "French Toast", type: "indica-strain", url: "https://www.leafly.com/strains/french-toast" },	
  { name: "Frost’d Flakes", type: "indica-strain", url: "https://weedmaps.com/strains/frosted-flakes" },	
  { name: "Frosted Cherry Cake", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/frosted-cakes" },	
  { name: "Frosted Cherry Cookies", type: "indica-strain", url: "https://www.leafly.com/strains/frosted-cherry-cookies" },	
  { name: "Frosted Cream Puffs", type: "hybrid-strain", url: "https://buylowgreen.com/product/frosted-cream-puffs/" },	
  { name: "Frosted Gumbo", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/frosted-gumbo" },	
  { name: "Fruit Loopz", type: "indica-strain", url: "https://growdiaries.com/strains/fruity-loopz" },	
  { name: "Fruity Chronic Juice", type: "indica-strain", url: "https://www.leafly.com/strains/fruity-chronic-juice" },	
  { name: "Funk Master", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/funkmaster" },	
  { name: "Funky Charms", type: "hybrid-strain", url: "https://www.leafly.com/strains/funky-charms" },	
  { name: "Galactic Death Star", type: "indica-strain", url: "https://www.leafly.com/strains/death-star" },	
  { name: "Galactic Glue", type: "hybrid-strain", url: "https://www.leafly.com/strains/galactic-glue" },	
  { name: "Galactic Haze", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/galactic-haze" },	
  { name: "Garlic Breath", type: "indica-strain", url: "https://www.leafly.com/strains/garlic-icing" },	
  { name: "Garlic Cake", type: "sativa-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/garlic-cake" },	
  { name: "Garlic Cookies", type: "indica-strain", url: "https://www.leafly.com/strains/gmo-cookies" },	
  { name: "Garlic Fingers", type: "indica-strain", url: "https://www.leafly.com/strains/garlic-bud" },	
  { name: "Gary Payton", type: "hybrid-strain", url: "https://www.leafly.com/strains/gary-payton" },	
  { name: "Gas Chamber", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/gas-chamber" },	
  { name: "Gas Mask", type: "indica-strain", url: "https://www.leafly.com/strains/gas-mask" },	
  { name: "Gasberry Pie", type: "indica-strain", url: "https://www.leafly.com/strains/gas-berry" },	
  { name: "Gastro Pop", type: "hybrid-strain", url: "https://www.leafly.com/strains/gastro-pop" },	
  { name: "Gelato", type: "hybrid-strain", url: "https://www.leafly.com/strains/gelato" },	
  { name: "Gelato 33", type: "hybrid-strain", url: "https://www.leafly.com/strains/gelato-33" },	
  { name: "Gelato Cake", type: "indica-strain", url: "https://www.leafly.com/strains/gelato-cake" },	
  { name: "Gelato Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/gelato-cookies" },	
  { name: "Ghost Gelato", type: "hybrid-strain", url: "https://valuebuds.com/products/good-supply-ghost-gelato-ind-dried-7g-alberta" },	
  { name: "Ghost OG", type: "hybrid-strain", url: "https://www.leafly.com/strains/ghost-og" },	
  { name: "Ghost Train Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/ghost-train-haze" },	
  { name: "Giesel Cookies", type: "indica-strain", url: "https://www.leafly.com/strains/giesel-cookies" },	
  { name: "Girl Scout Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/girl-scout-cookies" },	
  { name: "Glookies", type: "indica-strain", url: "https://www.leafly.com/strains/glookies" },	
  { name: "GMO Cookies", type: "indica-strain", url: "https://www.leafly.com/strains/gmo-cookies" },
  { name: "GMO Kush", type: "indica-strain", url: "https://shopcannabisnl.com/products/big-bag-o-buds-joints-gmo-kush-pre-roll" },	
  { name: "God Bud", type: "indica-strain", url: "https://www.leafly.com/strains/god-bud" },	
  { name: "Godfather OG", type: "indica-strain", url: "https://www.leafly.com/strains/godfather-og" },	
  { name: "Gods Gift", type: "indica-strain", url: "https://www.leafly.com/strains/gods-gift" },	
  { name: "Gods Green Crack", type: "hybrid-strain", url: "https://www.leafly.com/strains/gods-green-crack" },	
  { name: "Goldberry", type: "indica-strain", url: "https://www.leafly.com/strains/goldberry" },	
  { name: "Golden Goat", type: "hybrid-strain", url: "https://www.leafly.com/strains/golden-goat" },	
  { name: "Golden Pineapple", type: "hybrid-strain", url: "https://www.leafly.com/strains/golden-pineapple" },	
  { name: "Gooberry", type: "indica-strain", url: "https://www.leafly.com/strains/gooberry" },	
  { name: "Gorilla Berry", type: "indica-strain", url: "https://bulkweedinbox.cc/product/gorilla-berry/" },	
  { name: "Gorilla Bomb", type: "hybrid-strain", url: "https://www.leafly.com/strains/gorilla-bomb" },	
  { name: "Gorilla Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/gorilla-cookies" },	
  { name: "Gorilla Glue", type: "hybrid-strain", url: "https://www.leafly.com/strains/gorilla-glue" },	
  { name: "Gorilla Glue #4", type: "hybrid-strain", url: "https://www.leafly.com/strains/gorilla-glue-4" },	
  { name: "Gorilla Goo", type: "hybrid-strain", url: "https://www.leafly.com/strains/gorilla-goo" },	
  { name: "Gorilla Za", type: "hybrid-strain", url: "https://canna4less.ca/menu/downtown/products/endgame-207578/7g/gorilla-za-2818122/" },
  { name: "Gouda Berry", type: "hybrid-strain", url: "https://www.leafly.com/strains/goudaberry" }, 
  { name: "Grand Daddy Bruce", type: "indica-strain", url: "https://www.leafly.com/strains/grandaddy-bruce" },	
  { name: "Grandi Guava", type: "hybrid-strain", url: "https://www.leafly.com/strains/grandi-guava" },	
  { name: "Grape Ape", type: "indica-strain", url: "https://www.leafly.com/strains/grape-ape" },	
  { name: "Grape Cake", type: "indica-strain", url: "https://www.leafly.com/strains/grape-cake" },	
  { name: "Grape Cream Cake", type: "indica-strain", url: "https://www.leafly.com/strains/grape-cream-cake" },	
  { name: "Grape Crush", type: "indica-strain", url: "https://www.leafly.com/strains/grape-krush" },	
  { name: "Grape God", type: "hybrid-strain", url: "https://www.leafly.com/strains/grape-god" },	
  { name: "Grape Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/grape-kush" },	
  { name: "Grape Pie", type: "indica-strain", url: "https://www.leafly.com/strains/grape-pie" },	
  { name: "Grape Runtz", type: "indica-strain", url: "https://www.leafly.com/strains/grape-runtz" },	
  { name: "Grape Soda", type: "hybrid-strain", url: "https://www.leafly.com/strains/grape-soda" },	
  { name: "Grape Stomper", type: "hybrid-strain", url: "https://buyweedpacks.co/product/grape-stomper/" },	
  { name: "Grapes and Cream", type: "hybrid-strain", url: "https://www.leafly.com/strains/grapes-n-cream" },	
  { name: "Greasy Bubba", type: "indica-strain", url: "https://wccannabis.cc/greasy-bubba-the-ultimate-breakdown-you-need/" },	
  { name: "Great White Shark", type: "indica-strain", url: "https://greensociety.cc/product/great-white-shark/" },	
  { name: "Green Crack", type: "sativa-strain", url: "https://www.leafly.com/strains/green-crack" },	
  { name: "Green Widow", type: "indica-strain", url: "https://cheapweed.io/shop/marijuana-flowers/hybrid/green-widow/" },	
  { name: "Gushers", type: "hybrid-strain", url: "https://bulkweedinbox.cc/product/gushers/" },	
  { name: "Gypsy Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/gypsy-kush" },	
  { name: "Hash Bar", type: "indica-strain", url: "https://www.leafly.com/strains/hashbar-og" },	
  { name: "Hawaiian Snow", type: "sativa-strain", url: "https://www.leafly.com/strains/hawaiian-snow" },	
  { name: "Hawaiian", type: "sativa-strain", url: "https://www.leafly.com/strains/hawaiian-sativa" },	
  { name: "Headband", type: "hybrid-strain", url: "https://www.leafly.com/strains/headband" },	
  { name: "Headbanger", type: "sativa-strain", url: "https://www.leafly.com/strains/headbanger" },	
  { name: "Hella Jelly", type: "sativa-strain", url: "https://www.leafly.com/strains/hella-jelly" },	
  { name: "Hells OG 2.0", type: "hybrid-strain", url: "https://www.leafly.com/strains/hells-og" },	
  { name: "High Octane", type: "indica-strain", url: "https://wccannabis.cc/product/high-octane-aaaa/" },	
  { name: "Hindu Kush", type: "indica-strain", url: "https://www.leafly.com/strains/hindu-kush" },	
  { name: "Holy Grail", type: "indica-strain", url: "https://www.leafly.com/strains/holy-grail-kush" },	
  { name: "Honah Lee Haze", type: "sativa-strain", url: "https://www.420pm.ca/shop-whyte-ave-cannabis?dtche%5Bproduct%5D=honah-lee-haze" },	
  { name: "Honey Badger", type: "hybrid-strain", url: "https://www.leafly.com/strains/honey-badger-haze" },	
  { name: "Honey Badger Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/honey-badger-haze" },	
  { name: "Huckleberry", type: "indica-strain", url: "https://www.leafly.com/strains/huckleberry" },	
  { name: "Huckleberry DesStar", type: "sativa-strain", url: "https://www.leafly.com/strains/huckleberry-desstar" },	
  { name: "I Pot", type: "unknown-strain", url: "" }, 	
  { name: "Ice Cream", type: "hybrid-strain", url: "https://www.leafly.com/strains/ice-cream" },	
  { name: "Ice Cream Cake", type: "indica-strain", url: "https://www.leafly.com/strains/ice-cream-cake" },	
  { name: "Ice Wine", type: "hybrid-strain", url: "https://www.leafly.com/strains/ice-wine" },	
  { name: "Ice Wreck", type: "hybrid-strain", url: "https://www.leafly.com/strains/ice-wreck" },	
  { name: "Incredible Hulk", type: "sativa-strain", url: "https://www.leafly.com/strains/incredible-hulk" },	
  { name: "Inzane in the Membrane", type: "sativa-strain", url: "https://www.leafly.com/strains/inzane-in-the-membrane" },	
  { name: "Island Pink Kush", type: "indica-strain", url: "https://wccannabis.cc/product/island-pink-kush-aaaa-2/" },	
  { name: "Italian Ice", type: "indica-strain", url: "https://www.leafly.com/strains/italian-ice" },	
  { name: "Jack Frost", type: "sativa-strain", url: "https://www.leafly.com/strains/jack-frost" },	
  { name: "Jager", type: "indica-strain", url: "https://www.leafly.com/strains/jager" },	
  { name: "Jamacian Gold", type: "unknown-strain", url: "" },	
  { name: "Jean Guy", type: "sativa-strain", url: "https://www.leafly.com/strains/jean-guy" },	
  { name: "Jelly Cocktail", type: "hybrid-strain", url: "https://weedpedia.ca/product/jelly-cocktail/" },	
  { name: "Jet Fuel", type: "sativa-strain", url: "https://www.leafly.com/strains/jet-fuel" },
  { name: "Jet Fuel Pie", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/jet-fuel-pie" },
  { name: "Juicy Fruit", type: "hybrid-strain", url: "https://www.leafly.com/strains/juicy-fruit" },	
  { name: "Jungle Fumes", type: "indica-strain", url: "https://peicannabiscorp.com/product/jungle-fumes/" },	
  { name: "K Train", type: "indica-strain", url: "https://www.leafly.com/strains/k-train" },	
  { name: "Kali Mist", type: "sativa-strain", url: "https://www.leafly.com/strains/kali-mist" },	
  { name: "Khalifa Mintz", type: "hybrid-strain", url: "https://wccannabis.cc/product/khalifa-mintz-aaaa/" },	
  { name: "Killer OG", type: "indica-strain", url: "https://bulkweedinbox.cc/product/killer-og/" },	
  { name: "King Bubba", type: "indica-strain", url: "https://topshelfbc.cc/king-bubba/" },	
  { name: "King Tut", type: "sativa-strain", url: "https://bulkweedbc.cc/king-tut/" },	
  { name: "Krypto Kronic", type: "hybrid-strain", url: "https://www.leafly.com/strains/krypto-chronic" },	
  { name: "LA Confidential", type: "indica-strain", url: "https://www.leafly.com/strains/la-confidential" },	
  { name: "LA Wedding Pop", type: "sativa-strain", url: "https://www.leafly.com/strains/la-wedding-pop" },	
  { name: "Lady Boss", type: "hybrid-strain", url: "https://grasschief.cc/product/lady-boss/" },	
  { name: "Larry Bird", type: "hybrid-strain", url: "https://leafwell.com/cannabis-strains/larry-bird" },	
  { name: "Layer Cake", type: "indica-strain", url: "https://www.leafly.com/strains/layer-cake" },	
  { name: "Lazer Wolf", type: "sativa-strain", url: "https://montrosecannabis.ca/product/lazer-wolf-3-5g/" },	
  { name: "Lazy Berry Blaze", type: "indica-strain", url: "https://www.grassrootswindsor.com/lazy-berry-blaze-twd-indica/" },	
  { name: "Lemon Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/lemon-haze" },	
  { name: "Lemon Meringue", type: "sativa-strain", url: "https://www.leafly.com/strains/lemon-meringue" },	
  { name: "Lemon OG Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/lemon-og" },	
  { name: "Lemon Skunk", type: "hybrid-strain", url: "https://www.leafly.com/strains/lemon-skunk" },	
  { name: "Lemon Slushie", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/lemon-slushie" },	
  { name: "Lemon Zkittlez", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/lemon-zkittlez" },	
  { name: "Lions Milk", type: "indica-strain", url: "https://www.leafly.com/strains/lions-milk" },	
  { name: "Liquid Imagination", type: "sativa-strain", url: "https://www.leafly.com/strains/liquid-imagination" },	
  { name: "London Pound Cake", type: "indica-strain", url: "https://www.leafly.com/strains/london-poundcake" },	
  { name: "Lucky Charms", type: "hybrid-strain", url: "https://www.leafly.com/strains/lucky-charms" },	
  { name: "Lyeche Kush", type: "indica-strain", url: "https://www.leafly.com/strains/lychee" },	
  { name: "MAC Donut", type: "hybrid-strain", url: "https://mrclones.com/product/mac-donuts/" },	
  { name: "Macmosa", type: "sativa-strain", url: "https://www.leafly.com/strains/macmosa" },	
  { name: "Makaveli OG", type: "indica-strain", url: "https://speedgreens.co/product/makaveli-og-aaaa/" },	
  { name: "Mandarin Mints", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/mandarin-mints" },	
  { name: "Mango", type: "hybrid-strain", url: "https://www.leafly.com/strains/mango" },	
  { name: "Mango Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/mango-kush" },	
  { name: "Maple Leaf", type: "indica-strain", url: "https://www.leafly.com/strains/maple-leaf-indica" },	
  { name: "Mary OG", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/mary-og" },	
  { name: "Master Jedi", type: "hybrid-strain", url: "https://www.leafly.com/strains/master-jedi" },	
  { name: "Master Kush", type: "indica-strain", url: "https://www.leafly.com/strains/master-kush" },	
  { name: "Master Pink", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/master-pink" },	
  { name: "Master Yoda", type: "sativa-strain", url: "https://www.leafly.com/strains/master-yoda" },	
  { name: "Mataro Blue", type: "indica-strain", url: "https://www.leafly.com/strains/mataro-blue" },	
  { name: "Maui Berry", type: "hybrid-strain", url: "https://www.leafly.com/strains/maui-berry" },	
  { name: "Maui Wowie", type: "sativa-strain", url: "https://www.leafly.com/strains/maui-wowie" },	
  { name: "MC Pie Face", type: "indica-strain", url: "https://www.leafly.com/strains/pie-face-og" },	
  { name: "McFlurry", type: "hybrid-strain", url: "https://www.leafly.com/strains/mcflurry" },	
  { name: "McFritter", type: "hybrid-strain", url: "https://www.alchimiaweb.com/en/mcfritter-product-16936.php" },	
  { name: "Meat Breath", type: "indica-strain", url: "https://www.leafly.com/strains/meat-breath" },	
  { name: "Med Head", type: "unknown-strain", url: "" },	
  { name: "Megaton Melon #4", type: "hybrid-strain", url: "https://www.leafly.com/brands/ogen/products/ogen-megaton-melon-4-flower" },	
  { name: "Melonade", type: "sativa-strain", url: "https://www.leafly.com/strains/melonade" },	
  { name: "Midnight Sherb", type: "sativa-strain", url: "https://shopcannabisnl.com/products/figr-midnight-sherb" },   
  { name: "Mimosa", type: "sativa-strain", url: "https://www.leafly.com/strains/mimosa" },	
  { name: "Mimosa Cookies", type: "hybrid-strain", url: "https://app.jointcommerce.com/blog/category/cannabis-101/mimosa-cookies-by-mamiko-seeds-a-comprehensive-strain-guide/" },	
  { name: "Mint Froyo", type: "hybrid-strain", url: "https://budora.net/shop/cannabis/hybrid/mint-froyo-aaaa/" },	
  { name: "Miracle Alien Cookies", type: "hybrid-strain", url: "https://wccannabis.cc/product/miracle-alien-cookies-mac-aaaa/" },	
  { name: "MK Ultra", type: "indica-strain", url: "https://www.leafly.com/strains/mk-ultra" },	
  { name: "Mob Boss", type: "indica-strain", url: "https://www.leafly.com/strains/mob-boss" },	
  { name: "Monkey Breath", type: "indica-strain", url: "https://app.jointcommerce.com/blog/category/cannabis-101/monkey-breath-strain-a-comprehensive-strain-guide/" },	
  { name: "Monster Mass", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/monster-mass" },	
  { name: "Moon Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/moon-cookies" },	
  { name: "Morning Sun", type: "sativa-strain", url: "https://www.leafly.com/strains/morning-star" },	
  { name: "Mountain Mimosa", type: "sativa-strain", url: "" },	
  { name: "Munson", type: "indica-strain", url: "https://www.leafly.com/strains/munson" },	
  { name: "Neon Lambo", type: "hybrid-strain", url: "https://thecannavibes.com/products/neon-lambo-by-pure-sunfarms" },	
  { name: "Nightmare OG", type: "indica-strain", url: "https://www.leafly.com/strains/nightmare-og" },	
  { name: "Nirvana", type: "indica-strain", url: "https://www.leafly.com/strains/nirvana" },	
  { name: "Northern Lights", type: "indica-strain", url: "https://www.leafly.com/strains/northern-lights" },	
  { name: "Notorious OG", type: "indica-strain", url: "https://www.leafly.com/strains/notorious-og" },	
  { name: "Nuken", type: "indica-strain", url: "https://www.leafly.com/strains/nuken" },	
  { name: "Og God", type: "hybrid-strain", url: "https://weedmaps.com/strains/god-og" },
  { name: "OG Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/og-kush" },	
  { name: "OG Shark", type: "hybrid-strain", url: "https://www.leafly.com/strains/og-shark" },	
  { name: "Ogopogo Gold", type: "sativa-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/ogopogo-gold" },	
  { name: "Okanagan Frost", type: "indica-strain", url: "" },	
  { name: "One Punch", type: "hybrid-strain", url: "https://bulkweedinbox.cc/product/one-punch/" },	
  { name: "Orange Creamsicle", type: "hybrid-strain", url: "https://www.leafly.com/strains/orange-creamsicle" },	
  { name: "Orange Crush", type: "sativa-strain", url: "https://www.leafly.com/strains/orange-crush" },	
  { name: "Oreoz", type: "hybrid-strain", url: "https://www.leafly.com/strains/oreoz" },	
  { name: "Outlaw", type: "indica-strain", url: "https://www.leafly.com/strains/outlaw" },	
  { name: "Overlord OG", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/overlord-og" },	
  { name: "Pablo Escobar", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/pablo-escobar" },	
  { name: "Pablos Revenge", type: "indica-strain", url: "https://www.leafly.com/strains/pablos-revenge" },	
  { name: "Panama Red", type: "sativa-strain", url: "https://www.leafly.com/strains/panama-red" },	
  { name: "Papaya", type: "hybrid-strain", url: "https://www.leafly.com/strains/papaya" },	
  { name: "Papaya Cake", type: "indica-strain", url: "https://www.leafly.com/strains/papaya-cake" },	
  { name: "Papaya Punch", type: "hybrid-strain", url: "https://www.leafly.com/strains/papaya-punch" },	
  { name: "Peach Runtz", type: "hybrid-strain", url: "https://weedmaps.com/strains/peach-runtz" },	
  { name: "Peanut Butter Breath", type: "indica-strain", url: "https://www.leafly.com/strains/peanut-butter-breath" },	
  { name: "Peyote Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/peyote-cookies" },	
  { name: "Pie Face", type: "indica-strain", url: "https://www.leafly.com/strains/pie-face-og" },	
  { name: "Pie Hoe", type: "indica-strain", url: "https://www.leafly.com/strains/pie-hoe" },	
  { name: "Pine Tar Kush", type: "indica-strain", url: "https://www.leafly.com/strains/pine-tar-kush" },	
  { name: "Pineapple Express", type: "hybrid-strain", url: "https://www.leafly.com/strains/pineapple-express" },	
  { name: "Pineapple Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/pineapple-kush" },	
  { name: "Pineapple Mimosa", type: "sativa-strain", url: "https://www.leafly.com/strains/pineapple-mimosa" },	
  { name: "Pineapple Punch", type: "hybrid-strain", url: "https://www.leafly.com/strains/pineapple-punch" },	
  { name: "Pink", type: "hybrid-strain", url: "https://www.leafly.com/strains/pink-20" },	
  { name: "Pink Anxiety", type: "hybrid-strain", url: "https://www.leafly.com/strains/pink-anxiety" },	
  { name: "Pink Bubba", type: "indica-strain", url: "https://www.leafly.com/strains/pink-bubba" },	
  { name: "Pink Candy Kush", type: "hybrid-strain", url: "https://www.leafly.com/strains/pink-candy-kush" },	
  { name: "Pink Comatose", type: "indica-strain", url: "https://mmjexpress.cc/product/pink-comatose-aaaa/" },	
  { name: "Pink Crack", type: "sativa-strain", url: "https://wccannabis.cc/product/pink-crack-aaaa/" },	
  { name: "Pink Gas", type: "indica-strain", url: "https://www.leafly.com/strains/pink-gas" },	
  { name: "Pink Gas Mask", type: "indica-strain", url: "https://wccannabis.cc/product/pink-gas-mask-aaaa-2/" },	
  { name: "Pink Kush", type: "indica-strain", url: "https://www.leafly.com/strains/pink-kush" },	
  { name: "Pink Kush Mints", type: "indica-strain", url: "https://www.tncc.ca/product/big-bag-o-buds-pink-kush-mints/" },
  { name: "Pink Octane", type: "hybrid-strain", url: "https://www.leafly.com/brands/greenseal-cannabis-co/products/greenseal-cannabis-co-pink-octane-3-5g-flower-ontario-flower" },	
  { name: "Pink Panties", type: "indica-strain", url: "https://www.leafly.com/strains/pink-panties" },	
  { name: "Pink Push Pop", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/pink-push-pop" },	
  { name: "Pink Unicorn", type: "hybrid-strain", url: "https://wccannabis.cc/product/pink-unicorn-aa/" },	
  { name: "Platinum Death", type: "indica-strain", url: "https://www.comparethestrain.ca/death-bubba-vs-platinum-bubba-kush/" },
  { name: "Platimun Girl Scout Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/platinum-girl-scout-cookies" },	
  { name: "Platinum Gorilla Glue #4", type: "hybrid-strain", url: "https://www.leafly.com/brands/gg-strains/products/gg-strains-gg4-aka-gg-4" },	
  { name: "Platinum Jelly Breath", type: "hybrid-strain", url: "https://www.leafly.com/strains/platinum-jelly" },	
  { name: "Ponderosa Pine", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/ponderosa-pine" },	
  { name: "Poontang Pie", type: "hybrid-strain", url: "https://www.leafly.com/strains/poon-tang-pie" },	
  { name: "Pot of Gold", type: "indica-strain", url: "https://www.leafly.com/strains/pot-of-gold" },	
  { name: "Purple Afghan", type: "indica-strain", url: "https://www.leafly.com/strains/purple-afghani" },	
  { name: "Purple Bruce Banner", type: "hybrid-strain", url: "" },	
  { name: "Purple Bubba", type: "indica-strain", url: "https://www.leafly.com/strains/purple-bubba" },	
  { name: "Purple Caviar", type: "indica-strain", url: "https://wtfcannabis.io/product/purple-caviar/" },	
  { name: "Purple Certz", type: "indica-strain", url: "https://mrhempflower.com/product/purple-certz/" },	
  { name: "Purple Cheese", type: "hybrid-strain", url: "https://www.leafly.com/strains/purple-cheese" },	
  { name: "Purple Churro", type: "hybrid-strain", url: "https://www.leafly.com/strains/purple-churro" },	
  { name: "Purple Crack", type: "sativa-strain", url: "https://www.leafly.com/strains/purple-crack" },	
  { name: "Purple Dank", type: "indica-strain", url: "" },	
  { name: "Purple Death Star", type: "indica-strain", url: "" },	
  { name: "Purple Drank Breath", type: "indica-strain", url: "https://www.bulkbuddy.co/product/purple-dank-breath-strain-craft/" },	
  { name: "Purple Dream", type: "hybrid-strain", url: "https://www.leafly.com/strains/purple-dream" },	
  { name: "Purple Elephant", type: "indica-strain", url: "https://www.leafly.com/strains/purple-elephant" },	
  { name: "Purple God", type: "indica-strain", url: "https://www.leafly.com/strains/purple-god" },	
  { name: "Purple Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/purple-haze" },	
  { name: "Purple Huckleberry", type: "indica-strain", url: "" },	
  { name: "Purple Kush", type: "indica-strain", url: "https://www.leafly.com/strains/purple-kush" },	
  { name: "Purple Panty Dropper", type: "indica-strain", url: "https://www.leafly.com/strains/purple-panty-dropper" },	
  { name: "Purple Pornstar", type: "indica-strain", url: "" },	
  { name: "Purple Rose", type: "hybrid-strain", url: "https://www.leafly.com/strains/purple-roze" },	
  { name: "Purple Space Cookies", type: "hybrid-strain", url: "https://wccannabis.cc/product/purple-space-cookies-aaaa-2/" },	
  { name: "Purple Trainwreck", type: "hybrid-strain", url: "https://www.leafly.com/strains/purple-trainwreck" },	
  { name: "Purple Tropicana", type: "hybrid-strain", url: "https://wccannabis.cc/product/purple-tropicana-aaaa/" },	
  { name: "Purple Tuna", type: "indica-strain", url: "https://bulkweedinbox.cc/product/purple-tuna/" },	
  { name: "Purple Urkle", type: "indica-strain", url: "https://www.leafly.com/strains/purple-urkle" },	
  { name: "Purple Vanilla Frosting", type: "hybrid-strain", url: "https://bulkweedinbox.cc/product/purple-vanilla-frosting/" },	
  { name: "Race Car", type: "sativa-strain", url: "" },	
  { name: "Rainbow Cupcake", type: "hybrid-strain", url: "" },	
  { name: "Rainbow Skittles", type: "hybrid-strain", url: "https://www.leafly.com/strains/rainbow-zkittlez" },	
  { name: "Recon OG", type: "indica-strain", url: "" },	
  { name: "Revolver", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/revolver" },	
  { name: "Rockstar", type: "indica-strain", url: "https://www.leafly.com/strains/rockstar" },	
  { name: "Rockstar Peanut Butter", type: "hybrid-strain", url: "https://www.bulkbuddy.co/product/peanut-butter-rockstar-strain/" },	
  { name: "Romulan", type: "indica-strain", url: "https://www.leafly.com/strains/romulan" },
  { name: "Rooster Call", type: "sativa-strain", url: "https://www.cannabis-nb.com/01/all/menu/dried-flower/whole-buds/catch-me-outside-rooster-call-sativa/" },
  { name: "Royal Gorilla", type: "hybrid-strain", url: "https://www.leafly.com/strains/royal-gorilla" },	
  { name: "Royal Highness", type: "hybrid-strain", url: "https://www.leafly.com/strains/royal-highness" },	
  { name: "Sacre Bleu", type: "sativa-strain", url: "https://www.numocannabis.com/product/erwhat-sacre-bleu-3-5g-dried-flower/" },
  { name: "Sasquatch Sap", type: "sativa-strain", url: "https://www.leafly.ca/strains/sasquatch-sap"},
  { name: "Scooby Snacks", type: "hybrid-strain", url: "https://mmjexpress.cc/product/scooby-snacks-aa/" },	
  { name: "Scoops", type: "indica-strain", url: "https://www.hytiva.com/strains/hybrid/scoops" },	
  { name: "SFV", type: "hybrid-strain", url: "https://www.leafly.com/strains/sfv-og" },	
  { name: "Shark Bite", type: "hybrid-strain", url: "https://www.leafly.com/strains/shark-bite" },	
  { name: "Shark Shock", type: "hybrid-strain", url: "https://www.leafly.com/strains/shark-shock" },	
  { name: "Sherbert Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/sherbet-cookies" },	
  { name: "Shipwreck", type: "indica-strain", url: "https://www.leafly.com/strains/shipwreck" },	
  { name: "Shishkaberry", type: "indica-strain", url: "https://www.leafly.com/strains/shishkaberry" },	
  { name: "Silver Death Bubba", type: "indica-strain", url: "" },	
  { name: "Silver Surfer", type: "hybrid-strain", url: "https://www.leafly.com/strains/silver-surfer" },	
  { name: "Sirius Black", type: "indica-strain", url: "https://www.leafly.com/strains/sirius-black" },	
  { name: "Sky Cake", type: "hybrid-strain", url: "" },	
  { name: "Skywalker OG", type: "indica-strain", url: "https://www.leafly.com/strains/skywalker-og" },	
  { name: "Sleepy Joe", type: "indica-strain", url: "" },	
  { name: "Slow Lane", type: "hybrid-strain", url: "https://www.leafly.com/strains/slow-lane" },	
  { name: "Slurricane", type: "indica-strain", url: "https://www.leafly.com/strains/slurricane" },	
  { name: "Slurricane x Geleto", type: "hybrid-strain", url: "" },	
  { name: "Slurry Crasher", type: "hybrid-strain", url: "https://www.leafly.com/strains/slurricrasher" },	
  { name: "Snoop Dogg", type: "hybrid-strain", url: "https://www.leafly.com/strains/snoop-dogg-og" },	
  { name: "Sonic Lemon Fuel", type: "sativa-strain", url: "https://spinachcannabis.com/strains/sonic-lemon-fuel/" },	
  { name: "Sophies Breath", type: "indica-strain", url: "https://www.leafly.com/strains/sophie-s-breath" },	
  { name: "Sour Cheese", type: "hybrid-strain", url: "https://www.leafly.com/strains/sour-chees" },	
  { name: "Sour Diesel", type: "sativa-strain", url: "https://www.leafly.com/strains/sour-diesel" },	
  { name: "Sour Dream", type: "hybrid-strain", url: "https://www.leafly.com/strains/sour-dream" },	
  { name: "Space Age Cake", type: "indica-strain", url: "https://www.leafly.com/brands/phenix-cannabis/products/phenix-cannabis-space-age-cake-flower" },	
  { name: "Space Cake", type: "hybrid-strain", url: "https://www.leafly.com/strains/space-cake" },	
  { name: "Space Goblins", type: "sativa-strain", url: "https://cannacabana.com/products/space-goblins" },	
  { name: "Space Queen", type: "hybrid-strain", url: "https://www.leafly.com/strains/space-queen" },	
  { name: "Stankasaurus", type: "indica-strain", url: "https://www.leafly.com/strains/stankasaurus" },	
  { name: "Stinky Pinky", type: "indica-strain", url: "https://www.leafly.com/strains/stinky-pinky" },	
  { name: "Stinky Pussy", type: "indica-strain", url: "https://www.buybulkweed.ca/product/stinky-pussy/" },	
  { name: "Strawberries and Cream", type: "hybrid-strain", url: "https://www.leafly.com/strains/strawberries-and-cream" },	
  { name: "Strawberry Banana", type: "hybrid-strain", url: "https://www.leafly.com/strains/strawberry-banana" },	
  { name: "Strawberry Bubba", type: "indica-strain", url: "" },	
  { name: "Strawberry Cheezequake", type: "hybrid-strain", url: "https://fikacannabis.com/products/3saints-strawberry-cheezequake" },	
  { name: "Strawberry Lemonade", type: "sativa-strain", url: "https://www.leafly.com/strains/strawberry-lemonade" },	
  { name: "Sugar Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/sugar-cookies" },	
  { name: "Sundae Driver", type: "hybrid-strain", url: "https://www.leafly.com/strains/sundae-driver" },	
  { name: "Sunflower Sunshine", type: "sativa-strain", url: "https://bulkweedinbox.cc/product/sunflower-sunshine/" },	
  { name: "Sunset Sherbert", type: "indica-strain", url: "https://www.leafly.com/strains/sunset-sherbert" },	
  { name: "Sunshine Bubble Kush", type: "hybrid-strain", url: "https://www.grassrootswindsor.com/sunshine-bubble-kush-figr/" },	
  { name: "Super Glue", type: "hybrid-strain", url: "https://www.leafly.com/strains/superglue" },	
  { name: "Super Pink", type: "hybrid-strain", url: "https://www.leafly.com/strains/super-pink" },	
  { name: "Super Silver Haze", type: "sativa-strain", url: "https://www.leafly.com/strains/super-silver-haze" },	
  { name: "Super Sonic Blizzard", type: "hybrid-strain", url: "https://elev8seeds.com/strains/supersonic-blizzard/" },	
  { name: "Super Sour Widow", type: "hybrid-strain", url: "https://www.leafly.com/strains/super-sour-widow" },	
  { name: "Supreme Blueberry", type: "indica-strain", url: "https://wccannabis.cc/product/supreme-blueberry-aaaa/" },	
  { name: "Sweet Deep Grapefruit", type: "indica-strain", url: "https://www.leafly.com/strains/sweet-deep-grapefruit" },	
  { name: "Sweet Pink Grapefruit", type: "hybrid-strain", url: "https://www.leafly.com/strains/sweet-pink-grapefruit" },	
  { name: "Sweet Tooth", type: "hybrid-strain", url: "https://www.leafly.com/strains/sweet-tooth" },	
  { name: "Tally Mon", type: "hybrid-strain", url: "https://www.leafly.com/strains/tally-mon" },	
  { name: "Tangerine Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/tangerine-cookies" },	
  { name: "Tangerine Dream", type: "hybrid-strain", url: "https://www.leafly.com/strains/tangerine-dream" },	
  { name: "Tart Pop", type: "hybrid-strain", url: "" },	
  { name: "Tear Gas", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/tear-gas" },	
  { name: "The Force", type: "hybrid-strain", url: "https://www.leafly.com/strains/force-og" },	
  { name: "The Fudd", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/fudd" },	
  { name: "The Glove", type: "indica-strain", url: "https://www.leafly.com/strains/the-glove" },	
  { name: "The Undercaker", type: "indica-strain", url: "https://select-cannabis.ca/product/the-undercaker-dried-flower-by-terp-town-collective/" },	
  { name: "Thin Mint GSC", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/thin-mint-girl-scout-cookies" },	
  { name: "Tom Ford", type: "indica-strain", url: "https://www.leafly.com/strains/tom-ford" },	
  { name: "Tootsie Roll", type: "indica-strain", url: "https://www.allbud.com/marijuana-strains/hybrid/tootsie-roll" },	
  { name: "Top Crop", type: "hybrid-strain", url: "https://www.leafly.com/dispensary-info/top-crop-ontario" },	
  { name: "Trainwreck", type: "sativa-strain", url: "https://www.leafly.com/strains/trainwreck" },	
  { name: "Triceratops", type: "hybrid-strain", url: "https://kushstation.co/product/triceratops/" },	
  { name: "Triple Burger", type: "hybrid-strain", url: "https://www.leafly.com/strains/triple-burger" },	
  { name: "Trophy Wife", type: "hybrid-strain", url: "https://www.leafly.com/strains/trophy-wife" },	
  { name: "Tropical Milkshake", type: "hybrid-strain", url: "https://select-cannabis.ca/product/tropical-milkshake-dried-flower-by-tam-tams/" },	
  { name: "Tropical Zkittlez", type: "indica-strain", url: "https://weedmaps.com/strains/tropical-zkittlez" },	
  { name: "Tropicana Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/tropicana-cookies" },	
  { name: "Tsunami", type: "sativa-strain", url: "https://www.leafly.com/strains/tsunami" },	
  { name: "Turbo Diesel", type: "hybrid-strain", url: "https://www.leafly.com/strains/turbo-diesel" },	
  { name: "Tuna Kush", type: "indica-strain", url: "https://www.leafly.com/strains/tuna-kush" },	
  { name: "Turbo Mind Warp", type: "hybrid-strain", url: "https://www.leafly.com/strains/turbo-mind-warp" },	
  { name: "Tutti Frutti", type: "hybrid-strain", url: "https://www.leafly.com/strains/tutti-frutti" },	
  { name: "TWA Lot #6", type: "hybrid-strain", url: "" },	
  { name: "Tyson OG", type: "indica-strain", url: "https://www.leafly.com/brands/high-mountain-health/products/high-mountain-health-tyson-og" },	
  { name: "UK Cheese", type: "hybrid-strain", url: "https://www.leafly.com/strains/uk-cheese" },	
  { name: "Unicorn Poop", type: "hybrid-strain", url: "https://www.leafly.com/strains/unicorn-poop" },	
  { name: "Vanilla Ice", type: "hybrid-strain", url: "https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/vanilla-ice" },	
  { name: "Vanilla Kush", type: "indica-strain", url: "https://www.leafly.com/strains/vanilla-kush" },	
  { name: "Velvet Apple #14", type: "hybrid-strain", url: "https://plantlifecannabis.com/product/ogen-velvet-apples-14/?change-location=edmonton-albany" },	
  { name: "Velvet Rose", type: "hybrid-strain", url: "" },	
  { name: "Venom OG", type: "indica-strain", url: "https://www.leafly.com/strains/venom-og" },	
  { name: "Violator OG", type: "indica-strain", url: "https://www.bulkbuddy.co/product/89-oz-promo-violator-og/" },	
  { name: "Vintage Blueberry", type: "indica-strain", url: "https://wccannabis.cc/product/vintage-blueberry-aaaa-2/" },	
  { name: "Violet Delight", type: "indica-strain", url: "https://www.leafly.com/strains/violet-delight" },	
  { name: "Wappa", type: "indica-strain", url: "https://www.leafly.com/strains/wappa" },	
  { name: "Watermelon Breath", type: "hybrid-strain", url: "https://www.my28grams.co/buy/watermelon-breath/" },	
  { name: "Wedding Cake", type: "hybrid-strain", url: "https://www.leafly.com/strains/wedding-cake" },	
  { name: "Wedding Crasher", type: "hybrid-strain", url: "https://www.leafly.com/strains/wedding-crasher" },	
  { name: "Wheres my bike", type: "sativa-strain", url: "https://www.leafly.com/strains/wheres-my-bike" },	
  { name: "White Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/white-cookies" },	
  { name: "White Death", type: "indica-strain", url: "https://www.leafly.com/strains/white-death" },	
  { name: "White Lightning", type: "sativa-strain", url: "https://www.leafly.com/strains/white-lightning" },	
  { name: "White Rhino", type: "hybrid-strain", url: "https://www.leafly.com/strains/white-rhino" },	
  { name: "White Runtz", type: "hybrid-strain", url: "https://www.leafly.com/strains/white-runtz" },	
  { name: "White Russian Cream", type: "hybrid-strain", url: "https://mmjexpress.cc/product/white-russian-cream-aaaa/" },	
  { name: "White Tahoe Cookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/white-tahoe-cookies" },	
  { name: "White Truffle", type: "indica-strain", url: "https://www.leafly.com/strains/white-truffle" },	
  { name: "White Widow", type: "hybrid-strain", url: "https://www.leafly.com/strains/white-widow" },	
  { name: "Wild Cherry", type: "hybrid-strain", url: "https://www.leafly.com/strains/wild-cherry" },	
  { name: "Willie's Kush Cake", type: "hybrid-strain", url: "https://www.iheartjane.com/products/560457/alvarez-cultivation-willie-s-kush-cake" },	
  { name: "Winter Frost", type: "hybrid-strain", url: "https://strainy.ca/strain/good-supply/winter-frost" },	
  { name: "Witches Breath", type: "indica-strain", url: "https://www.northatlanticseed.com/product/witches-breath-f-limited/" },
  { name: "Wooly Mammoth", type: "hybrid-strain", url: "https://quadzillacannabis.net/product/woolly-mammoth-super-rare/" },	
  { name: "Xach's Breath", type: "hybrid-strain", url: "" },	
  { name: "Yellow Fin Tuna", type: "indica-strain", url: "https://bulkweedinbox.cc/product/yellowfin-tuna/" },	
  { name: "ZaZa", type: "hybrid-strain", url: "https://www.leafly.com/strains/zaza" },	
  { name: "Zestopia", type: "hybrid-strain", url: "https://getsmokeys.com/products/3781-uncommon-zestopia" },	
  { name: "Zkittles Cake", type: "hybrid-strain", url: "https://www.altsol.co/genetics/zkittlez-cake" },	
  { name: "Zombie Breath", type: "indica-strain", url: "https://ganjaexpress.to/shop/buy-marijuana-buds-online/aaa-aaaa/69-oz-zombie-breath/" },	
  { name: "Zombie Kush", type: "indica-strain", url: "https://www.leafly.com/strains/zombie-kush" },	
  { name: "Zookies", type: "hybrid-strain", url: "https://www.leafly.com/strains/zookies" },	
  { name: "Zsweet", type: "hybrid-strain", url: "https://doobiecannabis.ca/products/er-what-zsweet" },		
];
